### ISSUE TITLE
Specifying python dependencies

### ISSUE THREAD

**Issue by robbertvc** [PyO3/pyo3-pack#159]
Hi! Thanks for the cool project!

Small question: is it possible to specify external python dependencies in a mixed pyo3-pack project layout? If the python part of a mixed project is dependent on some package, let's say `external_package==1.0.0`, is there any way of specifying this so that the following command:
```bash
pip install my_pyo3_package.whl
```
will automatically pull in the `external_package` dependency?

I was thinking about something analogous to the scripts definition in `Cargo.toml`:

```toml

[package.metadata.pyo3-pack.requires-dist]
external_package = "==1.0.0"
```
but could not find it in the docs. Is this possible?
